routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{slug}', 'PageController@show')->name('page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	// Route::get('pages', 'PageController@index')->name('pages.index');
	// Route::get('pages/{id}', 'PageController@show')->name('pages.show');
	Route::resource('pages', 'PageController');
	Route::resource('animals', 'AnimalController');
});

app/Animal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    protected $fillable = ['image', 'name', 'title', 'description', 'keywords', 'content'];

    public function images()
    {
        return $this->hasMany('App\AnimalImage');
    }
}

app/Http/Controllers/Admin/AnimalController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Animal;

class AnimalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Animal::all();
        return view('admin.animal.index', ['animals' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.animal.create');   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $animal = new Animal();
        $animal->fill($request->all());
        $animal->save();
        return redirect()->route('animals.index'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Animal::where('id', $id)->firstOrFail();
        return view('admin.animal.show', ['animal' => $data]);       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = Animal::where('id', $id)->firstOrFail();
        return view('admin.animal.edit', ['animal' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $animal = Animal::where('id', $id)->firstOrFail();
        $animal->fill($request->all());
        $animal->save();
        return redirect()->route('animals.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $animal = Page::where('id', $id)->firstOrFail();
        $animal->delete();
        return redirect()->route('animals.index');        
    }
}

app/Http/Controllers/AnimalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AnimalController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Animal::where('id', $id)->firstOrFail();
        return view('animal', ['animal' => $data]);
    }
}

resources/views/admin/animal/create.blade.php
<h1>Create animal</h1>
{!! Form::open(['url' => route('animals.store'), 'method' => 'post']) !!}
	@include('admin.animal.form')
{!! Form::close() !!}
<a href="{{ route('animals.index') }}">List</a>

resources/views/admin/animal/edit.blade.php
<h1>Edit {{ $animal->name }}</h1>
{!! Form::open(['url' => route('animals.update', ['id' => $animal->id]), 'method' => 'put']) !!}
	@include('admin.animal.form', ['animal' => $animal])
{!! Form::close() !!}
<a href="{{ route('animals.index') }}">List</a>
<a href="{{ route('animals.show', ['id' => $animal->id]) }}">Show</a>

resources/views/admin/animal/form.blade.php
<div>
	{{ Form::label('image', 'Image') }}
	{{ Form::text('image', isset($animal) ? $animal->image : '') }}
</div> 

<div>
	{{ Form::label('name', 'Name') }}
	{{ Form::text('name', isset($animal) ? $animal->name : '') }}
</div>

<div>
	{{ Form::label('content', 'Content') }}
	{!! Form::textarea('content', isset($animal) ? $animal->content : '') !!}
</div>

{{ Form::button('<i class="fas fa-home"></i>Send', ['type' => 'submit']) }}

resources/views/admin/animal/index.blade.php
<h1>Animal list</h1>
<ul>
	@foreach($animals as $animal)
		<li>
			<a href="{{ route('animals.show', ['id' => $animal->id]) }}">{{ $animal->name }}</a>
		</li>
	@endforeach
</ul>
<a href="{{ route('animals.create') }}">Create</a>

resources/views/admin/animal/show.blade.php
<h1>{{ $animal->name }}</h1>
<table>
	<tr>
		<th>Name</th><td>{{ $animal->name }}</td>
	</tr>
	<tr>
		<th>Title</th><td>{{ $animal->title }}</td>
	</tr>
	<tr>
		<th>Description</th><td>{{ $animal->description }}</td>
	</tr>
	<tr>
		<th>Keywords</th><td>{{ $animal->keywords }}</td>
	</tr>
	<tr>
		<th>Content</th><td>{{ $animal->content }}</td>
	</tr>
</table>
<ul>
	@foreach($animal->images as $image)
		<li>{{ $image->name }}</li>
	@endforeach
</ul>
<a href="{{ route('animals.index') }}">List</a>
<a href="{{ route('animals.edit', ['id' => $animal->id]) }}">Edit</a>
{!! Form::open(['url' => route('animals.destroy', ['id' => $animal->id]), 'method' => 'delete']) !!}
	{{ Form::button('<i class="fas fa-times"></i>Delete', ['type' => 'submit']) }}
{!! Form::close() !!}